// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlT68Ba1GylBOYjh5Zy874vUMXrEBz_ag',
    appId: '1:974574041538:web:9014ab5e28cdabc14d7e5b',
    messagingSenderId: '974574041538',
    projectId: 'acm-mobile-app-9c4b7',
    authDomain: 'acm-mobile-app-9c4b7.firebaseapp.com',
    databaseURL: 'https://acm-mobile-app-9c4b7-default-rtdb.firebaseio.com',
    storageBucket: 'acm-mobile-app-9c4b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIkCHC-B2F_lynd5uz9Ro81H_YZ49V7k',
    appId: '1:974574041538:android:372f2766f3b2ff254d7e5b',
    messagingSenderId: '974574041538',
    projectId: 'acm-mobile-app-9c4b7',
    databaseURL: 'https://acm-mobile-app-9c4b7-default-rtdb.firebaseio.com',
    storageBucket: 'acm-mobile-app-9c4b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbtDuMQMxb655IlJA_3MNHiPunkiijcqI',
    appId: '1:974574041538:ios:78deb70984f5f8204d7e5b',
    messagingSenderId: '974574041538',
    projectId: 'acm-mobile-app-9c4b7',
    databaseURL: 'https://acm-mobile-app-9c4b7-default-rtdb.firebaseio.com',
    storageBucket: 'acm-mobile-app-9c4b7.appspot.com',
    iosBundleId: 'com.example.acmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbtDuMQMxb655IlJA_3MNHiPunkiijcqI',
    appId: '1:974574041538:ios:74beb971d0b616e94d7e5b',
    messagingSenderId: '974574041538',
    projectId: 'acm-mobile-app-9c4b7',
    databaseURL: 'https://acm-mobile-app-9c4b7-default-rtdb.firebaseio.com',
    storageBucket: 'acm-mobile-app-9c4b7.appspot.com',
    iosBundleId: 'com.example.acmApp.RunnerTests',
  );
}
